### PR TITLE
Updated node-inspector

### PR DESCRIPTION
**Pull request by michaelBenin**
Allows me to use shrinkwrap.

See:

https://github.com/npm/npm/issues/8523

Verified it's working.

### CODE REVIEW

**Comment by michaelBenin** [comment]
@vesparny LMK if you have any questions. Thank you!

**Comment by vesparny** [comment]
@michaelBenin thanks I'll merge it asap

**Comment by tristanz** [comment]
+1

**Comment by michaelBenin** [comment]
@vesparny bump

**Pull request merged**
