### PR TITLE
Update node-inspector 1.0.0, fix error when install in node 7 +

### PR DESCRIPTION
**Pull request by dhiefphams**
Issue here: https://github.com/node-inspector/node-inspector/issues/992

### CODE REVIEW

**Comment by chevdor** [comment]
Nice PR @dhiefphams thanks for submitting it.
I was just hitting the same issue and this PR fixes it.

**Comment by dhiefphams** [comment]
@chevdor You're welcome :)

**Comment by dhiefphams** [comment]
But it seems that the maintainers is no longer active in this repo.

**Comment by vohtaski** [comment]
Sorry, but I don't have access anymore to this organization :(
I guess the best is that you fork it and publish your fork to the npm

**Comment by vesparny** [comment]
Hi, I'm happy to add anyone interested in maintaining a fork as a collaborator on npm.
Please give me your npm handles.

Thanks

**Comment by chevdor** [comment]
Hey it sounds like we are moving more than expected :) Thank you guys for the feedback.
I guess it would make sense to add @dhiefphams and @3y3.
You may add me as well. My handle on npm is also 'chevdor': https://www.npmjs.com/~chevdor

**Comment by vesparny** [comment]
Hi guys,

I have added @dhiefphams as the only maintainer on npm.

@chevdor please ask him to add yourself too.

I removed myself too.

Take good care :)

**Pull request closed without merging**
